"use client";
import { useState } from "react";
import Link from "next/link";
import type { TechniqueContract } from "@/lib/types";
type Entry = { slug: string; number: number; title: string; stage: string; principle: string; author: string; contract: TechniqueContract };
export function TechniqueFinder({ techniques }: { techniques: Entry[] }) {
  const [selected, setSelected] = useState<string[]>([]);
  const chosen = techniques.filter((t) => selected.includes(t.slug));
  return <section aria-label="Technique results"><div className="result-heading"><p>{techniques.length} {techniques.length === 1 ? "technique" : "techniques"}</p><p role="status">{selected.length ? `${selected.length} of 2 selected for comparison` : "Select up to two to compare"}</p></div>
    {chosen.length > 0 && <aside className="comparison-desk" aria-label="Selected technique comparison"><div className="section-heading"><h2>Your working set</h2><button className="text-link" onClick={() => setSelected([])}>Clear selection</button></div><p>Compatibility is a decision, not a badge. If both change the same role, choose one. Never stack attention effects.</p><div className="comparison-columns">{chosen.map((t) => <div key={t.slug}><h3><Link href={`/techniques/${t.slug}`}>{t.title} ↗</Link></h3><dl><dt>Use when</dt><dd>{t.contract.useWhen[0]}</dd><dt>Avoid when</dt><dd>{t.contract.avoidWhen[0]}</dd><dt>Evidence to collect</dt><dd>{t.contract.acceptance[0]}</dd><dt>Stop when</dt><dd>{t.contract.compatibility.stop}</dd></dl><button className="text-link" onClick={() => setSelected(selected.filter((s) => s !== t.slug))} aria-label={`Remove ${t.title} from comparison`}>Remove</button></div>)}</div></aside>}
    {techniques.length === 0 ? <div className="empty-desk"><h2>No techniques match this combination.</h2><p>Try fewer words or remove a problem, stage or author filter.</p><Link className="ink-button" href="/techniques">Reset the finder</Link></div> : <div className="technique-results">{techniques.map((t) => <article key={t.slug} className="technique-row"><span className="entry-number" aria-hidden="true">{String(t.number).padStart(2, "0")}</span><div><p className="eyebrow">{t.stage} / {t.author}</p><h2><Link href={`/techniques/${t.slug}`}>{t.title} <span aria-hidden="true">↗</span></Link></h2><p className="entry-principle">{t.principle}</p><details><summary>Use / avoid</summary><p><strong>Use:</strong> {t.contract.useWhen[0]}</p><p><strong>Avoid:</strong> {t.contract.avoidWhen[0]}</p></details></div><label className="compare-choice"><input type="checkbox" checked={selected.includes(t.slug)} disabled={selected.length === 2 && !selected.includes(t.slug)} onChange={() => setSelected(selected.includes(t.slug) ? selected.filter((s) => s !== t.slug) : [...selected, t.slug])} /><span className="sr-only">{t.title}: </span>Compare</label></article>)}</div>}
  </section>;
}
